#!/bin/bash

top="$(dirname $(readlink -f $0))/.."
source $top/etc/build_settings

mkdir -p $data_dir $build_dir $index_dir

if [ ! -f "$corpus" ]; then 
	wget -O - $corpus_url | gzip -cd > $corpus
	[ "$?" != "0" ] && exit 1 
fi

echo "Generating Training file for NR entity recognition"
$bin/pdc_normalize_4nr -v $corpus > ${build_dir}/pd_nr.txt || exit 1
$bin/ner_nr_tool ${build_dir}/pd_nr.txt > ${build_dir}/pd_nr_training.txt || exit 1

echo "Begin CRF Training"
crf_learn -t -c 4.0 -f 2 -p 1 $tmpl_dir/crf_ner_nr.tmpl ${build_dir}/pd_nr_training.txt ${index_dir}/crf_ner_nr.model || exit 1
