#!/bin/sh
TAG="people-daily"
TOP=$(dirname $(which $0))/..
RAW="$TOP/data_raw/${TAG}.txt"
USER_COMBINE="$TOP/data_raw/user-combine.txt"
if [ ! -r "$RAW" ]; then
	echo "can not find $RAWDIR/${TAG}.txt" >&2
	exit 1
fi
BUILD_DIR=$TOP/data_build
INDEX_DIR=$TOP/index
mkdir -p $BUILD_DIR
mkdir -p $INDEX_DIR
cat $USER_COMBINE | sed -e 's/^/1 /g' > ${BUILD_DIR}/combine.txt

$TOP/bin/pdc_tool -v -u ${RAW} > ${BUILD_DIR}/${TAG}.ugm.txt
$TOP/bin/lexicon_cli -v -b -i ${INDEX_DIR}/${TAG}.ugm.idx -s ${BUILD_DIR}/${TAG}.ugm.txt
$TOP/bin/lexicon_cli -v -b -i ${INDEX_DIR}/combine.idx -s ${BUILD_DIR}/combine.txt

