#!/bin/bash

top="$(dirname $(readlink -f $0))/.."
source $top/etc/build_settings

mkdir -p $data_dir $build_dir $index_dir

if [ ! -f "$corpus" ]; then 
	wget -O - $corpus_url | gzip -cd > $corpus
	[ "$?" != "0" ] && exit 1 
fi

echo "Generating Training file for NT entity recognition"
$bin/ner_tool -s $corpus -t nt > ${build_dir}/pd_nt_training.txt || exit 1

echo "Begin CRF Training"
crf_learn -t -c 4.0 -f 2 -p 1 $data_dir/nt.tmpl ${build_dir}/pd_nt_training.txt ${index_dir}/crf_ner_nt.model || exit 1
