#!/bin/bash

bin=$top/bin
data_dir=$top/data
build_dir=$top/build
index_dir=$top/index

corpus="$data_dir/people-daily.txt"
number_trailing="$data_dir/number-trailing.txt"
user_combine="$data_dir/user_combine.txt"
break="$data_dir/break.txt"

corpus_url="http://nlpbamboo.googlecode.com/files/people-daily.txt.gz" 
number_trailing_url="http://nlpbamboo.googlecode.com/files/number_trailing.txt"
