#!/usr/bin/env perl

use strict;

my %map;
while(<DATA>) {
	my ($key, $val) = split /\s+/;
	$map{lc($key)} = $val;
}

while(<>) {
	s!/(\w+)!sprintf("/%s", $map{lc($1)})!seg;
	print $_;
}

__DATA__
Ag 形语素 
a 形容词 
ad 副形词 
an 名形词 
Bg 区别语素 
b 区别词 
c 连词 
Dg 副语素 
d 副词 
e 叹词 
f 方位词 
g 语素 
h 前接成分 
i 成语 
j 简略语 
k 后接成分 
l 习用语 
Mg 数语素 
m 数词 
Ng 名语素 
n 名词 
nr 人名 
ns 地名 
nt 机构团体 
nx 外文字符 
nz 其它专名 
o 拟声词 
p 介词 
Qg 量语素 
q 量词 
Rg 代语素 
r 代词 
s 处所词 
Tg 时间语素 
t 时间词 
Ug 助语素 
u 助词 
Vg 动语素 
v 动词 
vd 副动词 
vn 名动词 
w 标点符号 
x 非语素字 
Yg 语气语素 
y 语气词 
z 状态词 
