#!/usr/bin/env perl

#
#  Copyright (c) 2008, detrox@gmail.com
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#      * Redistributions of source code must retain the above copyright
#        notice, this list of conditions and the following disclaimer.
#      * Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in the
#        documentation and/or other materials provided with the distribution.
#      * Neither the name of the <organization> nor the
#        names of its contributors may be used to endorse or promote products
#        derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY detrox@gmail.com ''AS IS'' AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL detrox@gmail.com BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

use strict;
use Data::Dumper;
use Getopt::Std;
use utf8;
use Encode qw/encode decode/;
use vars '$opt_n','$opt_v', '$opt_h';

################################################################################
#
# build Ngram lexicon
#
################################################################################

sub build_unigram_lexicon
{
	my $file = shift @_;
	my $n = shift @_;
	my $unknow = '$';
	my $i;

	my %lexicon = ();
	open FH, "<$file" or die "can not open $file";
	print STDERR "Building $n-gram Lexicon from $file: \n" if ($opt_v);
	while (<FH>) {
		chomp;
		$_ = decode('UTF-8', $_);
		my @ngram = split(/\s/, "$unknow "x$n);
		foreach (split(/\s+/)) {
			my $lex = $_;
			shift @ngram;
			push @ngram, $lex;
			$lexicon{"@ngram"}++;
			print STDERR "\r\t\t".keys(%lexicon)." items generated." if ($opt_v && keys(%lexicon) % 500 == 0);
		}
	}
	print STDERR "\r\t\t".keys(%lexicon)." items generated.\n" if ($opt_v);
	print encode("UTF-8", "$lexicon{$_} $_\n") foreach keys %lexicon;
	close FH;
}

################################################################################
#
# main
#
################################################################################


if (!getopts("hn:v") || $opt_h || !$ARGV[0]) {
	print "Usage: ngm_tool [OPTIONS] CORPUS\n";
	print "Convert People Daily Corpus to Lexicon\n";
	print "OPTIONS:\n";
	print "        -n N          build N-gram lexicon from corpus\n";
	print "        -v            verbose\n";
	print "\n";
	print "Author: jianingy <detrox\@gmail.com>\n";
}

&build_unigram_lexicon($ARGV[0], $opt_n) if ($opt_n);
