#!/usr/bin/env perl

use strict;
use Data::Dumper;
use Getopt::Std;
use utf8;
use Encode qw/encode decode/;
use vars '$opt_u','$opt_v';

################################################################################
#
# build unigram lexicon
#
################################################################################

sub build_unigram_lexicon
{
	my $file = shift @_;
	my %lexicon = ();
	open FH, "<$file";
	print STDERR "Building Unigram Lexicon: \n" if ($opt_v);
	while (<FH>) {
		chomp;
		$_ = decode('UTF-8', $_);
		my (undef, $_) = split(/\s+/, $_, 2);
		s/\[|\]\w+//g; # remove combined word	
		foreach (split(/\s+/)) {
			my ($lex, $attr) = split(/\//, $_, 2);
			# omit punctuation, Arab number, time and alpha
			next if $attr =~ /w|t/;
			next if $lex =~ /[0123456789０１２３４５６７８９]/;
			next if $lex =~ /[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ]/;
			$lexicon{$lex}++;
			print STDERR "\r\t\t".keys(%lexicon)." items processed." if ($opt_v && keys(%lexicon) % 500 == 0);
		}
	}
	print STDERR "\r\t\t".keys(%lexicon)." items processed.\n" if ($opt_v);
	print encode("UTF-8", "$lexicon{$_} $_\n") foreach keys %lexicon;
	close FH;
}

################################################################################
#
# main
#
################################################################################


if ( !getopts("uv") || (@ARGV < 1)) {
	print "Usage: ngm_tool [OPTIONS] CORPUS\n";
	print "\n";
	print "OPTIONS:\n";
	print "        -u            build unigram lexicon from CORPUS\n";
	print "        -v            verbose\n";
	print "\n";
	print "Author: jianingy <detrox\@gmail.com>\n";
}

my $file = @ARGV[0];
die "can not open file $file!\n" if (!-f $file);

&build_unigram_lexicon($file) if ($opt_u);
